# Generated by Django 3.2 on 2023-01-02 08:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=80)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('marca', models.CharField(choices=[('Motorola', 'Motorola'), ('Samsung', 'Samsung'), ('Lg', 'Lg'), ('Xiaomi', 'Xiaomi'), ('Sony', 'Sony'), ('Huawey', 'Huawey'), ('Chino', 'Chino'), ('Otro', 'Otro')], max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=40)),
                ('imei', models.CharField(blank=True, max_length=40)),
                ('falla', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fallas//%Y/%m/%d')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pago_seña', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Reparado', 'Reparado'), ('Irreparable', 'Irreparable'), ('Entregado', 'Entregado'), ('Entregado Irreparable', 'Entregado Irreparable')], default='Pendiente', max_length=40)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio_tecnico.cliente')),
            ],
        ),
    ]
