# Generated by Django 3.2 on 2022-12-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0002_auto_20221209_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TareasPendientes',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titulo',
            new_name='title',
        ),
    ]
